### ISSUE TITLE
Uncaught TypeError: _phaserShim2.default.Game is not a function

### ISSUE THREAD

**Issue by A11oW** [amowu/phaser-shim#1]
Hello. Thx for package.
But, I have some problem with him.
If I code this:

```
import Phaser from 'phaser-shim';
let game = new Phaser.Game(800, 600);
```

I have this error:

```
Uncaught TypeError: _phaserShim2.default.Game is not a function
```

But if I add in phaser-shim `module.export`  all work fine.

```
'use strict';

require('./dist/pixi');
require('./dist/phaser');

module.exports = Phaser;
```

For boilerplate project I use this rep https://github.com/anaibol/phaser-webpack-babel-boilerplate

**Comment by amowu** [comment]
OK, I will add this fix, thx so much :D
