### ISSUE TITLE
Cannot configure Phaser Version

### ISSUE THREAD

**Issue by marcus-robinson** [amowu/phaser-shim#3]
I followed the readme instructions and it worked great, but the shim used an old version of Phaser (2.4.4) instead of the latest (2.4.6).

Can we please have the ability to configure which version of Phaser to use? Or at least instructions on how we can manually configure a newer version? I will fork the project and see if I can sort it out, but please let me know if you have an easy fix for this. Thanks!

**Comment by amowu** [comment]
hi @marcus-robinson, I am sorry for late reply.

I have update phaser-shim to v2.4.6, and add a new [develop section](https://github.com/amowu/phaser-shim/commit/f47c7dd68054531cf7e4155bc9ec48d5e8522488) in README.md, that can help you to build any version by yourself.

thanks :-)

**Comment by marcus-robinson** [comment]
Awesome, thanks Amo, I'll check it out.
