### ISSUE TITLE
Shim TypeScript definition files.

### ISSUE THREAD

**Issue by nathanosdev** [amowu/phaser-shim#4]
Thanks for this module, works really well!

Just a slight improvement would be to allow for full support on ES6 style imports in TypeScript by shimming the phaser TypeScript definitions.

What I would like to be able to do is this:

``` javascript
import {Game, State} from 'phaser-shim';
```

This can be achieved by adding a `phaser-shim.d.ts` file like so:

``` javascript
/// <reference path="../node_modules/phaser/typescript/phaser.comments.d.ts" />

declare module 'phaser-shim' {
    export = Phaser;
}
```

Although it might be worth shimming both `phaser.comments.d.ts` as well as `phaser.d.ts`.
I can make a pull request to implement this if you like.

**Comment by amowu** [comment]
hi @AnimaMundi ! thank great feedback, I look forward to receiving your pull request. :-D

**Comment by amowu** [comment]
Hi @AnimaMundi, thank you so much, close #5.

**Comment by nathanosdev** [comment]
Awesome, glad to help! Although I just realized it would be clearer if the documentation was also updated, so I can do this over the weekend if you like.

**Comment by amowu** [comment]
@AnimaMundi :+1: :+1:
